# Question 4
# Import Random Library

''' Int this question, a list will have numbers like 1,2,3,4,5. It will be checked if a number in list is multiple of
5 it will be replaced by its power like if number is 5 then 25 will be there at its position. So, to implement this, I made
generate random list function that will give list of 10 numbers having number genereated by random function 
between 1 and 50. Range function is used with decrementing starting from 10 upto 1 by decrementing -1 from each
value of loop variable. It will return list at last. Replace multiples of 5 function will iterate over list using for loop.
New list of squares will be added by elements. If element of original is divisble by 5 by using mod operator then
it will be added as element**2, ** is power operator otherwise it will be added as it is. In this way, our new list
will contain numbers with powers if multiple of 5 and others as it is. After defining these functions, random_list
is generated by generate_random_list() and then  modified_list with replace_multiples_of_5(random_list).
At last, after generation of lists print statment is used as well to print data of them.'''
import random

def generate_random_list():
    """
    This function generates a list with 10 random integers between 1 and 50.
    """
    listGenerated = []
    # _ will server as loop for iterating 10 time to have 10 elements picked from 1 to 50 placed in list
    for _ in range(10,0,-1):
        listGenerated.append(random.randint(1, 50))
        
    return listGenerated

def replace_multiples_of_5(original):
    """
    Replaces elements in the list that are multiples of 5 with their squares.
    """
    listSquares = []
    for element in original:
        # It will check if element is divisble by 5 using mod operator
        if element % 5 == 0:
            listSquares.append(element ** 2)
        # If element is not multiple of 5, then add it as same.
        else:
            listSquares.append(element)          
    # Return new list  
    return listSquares

# Generate a random list by using generate_random_list()
random_list = generate_random_list()
# Replace multiples of 5 with their squares 
modified_list = replace_multiples_of_5(random_list)

# Prints Original List
print("Original list:", random_list)
# Print Modified List
print("Modified list:", modified_list)